apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hive
  name: hive-web
  namespace: 1-multiple-containers-pod
spec:
  containers:
  - image: nginx:stable
    name: hive-web
    ports:
    - containerPort: 80
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: content
    configMap:
      name: hive-content
      optional: false
