apiVersion: v1
kind: Service
metadata:
  namespace: 1-multiple-containers-pod
  name: hive-svc
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 80
  selector:
    app: hive
  type: ClusterIP
